test_queries = [
    "How do I reset my password?",
    "How can I reset my password?",
    "How do I reset my account password?",
    "I forgot my password",
    "I can't remember my password",
    "Help me recover my password",
    "Lost my login credentials",
    "What is the password policy?",
    "How long does a password need to be?",
    "Can I use special characters in my password?",
    "What's your refund policy?",
    "How do I contact support?",
    "Where can I find documentation?",
    "What are your business hours?",
    "How do I iterate over a list in Python?",
    "How to iterate through a list in Python?",
    "What's the syntax for looping over a Python list?",
    "How do I sort a list in Python?",
    "How do I reverse a list in Python?",
    "How do I filter a list in Python?",
    "What's the current exchange rate?",
    "What's today's weather?",
    "What's the latest news?",
    "Show me real-time stock prices",
    "What's my account balance?",
    "Show me my order history",
    "What's my current subscription?",
]